version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    labels:
      kompose.service.type: clusterip
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:9de28b80a316f745fe1c86707f6b16bc689ee6dc6cebe4c60911c87069a5eda6
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  data:
    labels:
      kompose.volume.type: persistentVolumeClaim