version: '3.6'
services:
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:e1e42e16f1a5a10228a53a0ab2d2d95c1aed552040a7abebbb12156f9f2c0697
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  db:
