schema:
  - http://localhost:4455/api/v1/graphql:
      headers:
        x-hasura-admin-secret: password

overwrite: true
generates:
  schema.graphql:
    plugins:
      - schema-ast
  ./src/generated/graphql.schema.json:
    plugins:
      - introspection
