schema:
  - http://localhost:4455/v1/graphql:
      headers:
        user-agent: codegen
        x-hasura-admin-secret: password
#        x-hasura-role: user

overwrite: true
generates:
  schema.graphql:
    plugins:
      - schema-ast
  ./src/generated/graphql.schema.json:
    plugins:
      - introspection
