apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.prod.yaml convert --volumes=configMap -c -o k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ctfg
  name: ctfg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ctfg
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.prod.yaml convert --volumes=configMap -c -o k8s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: ctfg
    spec:
      containers:
        - env:
            - name: CTFG_ADMIN_EMAIL
              value: admin@admin.com
            - name: CTFG_ADMIN_PASSWORD
              value: password
            - name: DB_DSN
              value: host=postgres user=postgres password=password sslmode=disable
            - name: DB_TYPE
              value: postgres
            - name: PORT
              value: "8000"
          image: ghcr.io/ctfg/ctfg@sha256:a3dcdefa08d3e46892d11afe85f11ae0e8eec5139e97e3e97a88848ac16466e1
          name: ctfg
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
