apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.prod.yaml convert --volumes=configMap -c -o k8s
    kompose.image-pull-secret: ghcr-pull-secret
    kompose.service.type: clusterip
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ctfg
  name: ctfg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ctfg
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.prod.yaml convert --volumes=configMap -c -o k8s
        kompose.image-pull-secret: ghcr-pull-secret
        kompose.service.type: clusterip
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: ctfg
    spec:
      containers:
        - env:
            - name: CTFG_ADMIN_EMAIL
              value: admin@admin.com
            - name: CTFG_ADMIN_PASSWORD
              value: password
            - name: DB_DSN
              value: host=postgres user=postgres password=password sslmode=disable
            - name: DB_TYPE
              value: postgres
            - name: PORT
              value: "8000"
          image: ghcr.io/ctfg/ctfg@sha256:ae12e4e683e1748903391cf642dc01faf0e1a64153e512cfef41730699340203
          name: ctfg
          ports:
            - containerPort: 8000
          resources: {}
      imagePullSecrets:
        - name: ghcr-pull-secret
      restartPolicy: Always
status: {}
