apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.prod.yaml convert --volumes=configMap -c -o k8s
    kompose.service.type: clusterip
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ctfg
  name: ctfg
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: ctfg
  type: ClusterIP
status:
  loadBalancer: {}
