apiVersion: v1
data:
  config.yaml: |
    version: 3
    endpoint: http://127.0.0.1:8080
    metadata_directory: metadata
    actions:
      kind: synchronous
      handler_webhook_baseurl: http://localhost:3000
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: hasura
  name: hasura-cm0
