apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml -f docker-compose.prod.yaml convert --volumes=configMap -c -o k8s
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kratos-migrate
  name: kratos-migrate
spec:
  containers:
    - args:
        - -c
        - /config/config.yaml
        - migrate
        - sql
        - -e
        - --yes
      env:
        - name: DSN
          value: postgres://postgres:postgrespassword@postgres:5432/lunatrace
      image: kratos-migrate
      name: kratos-migrate
      resources: {}
      volumeMounts:
        - mountPath: /config
          name: kratos-migrate-cm0
  restartPolicy: OnFailure
  volumes:
    - configMap:
        name: kratos-migrate-cm0
      name: kratos-migrate-cm0
status: {}
