apiVersion: v1
data:
  config.dev.yaml: |
    serve:
      public:
        base_url: http://localhost:4455/api/kratos/

    selfservice:
      default_browser_return_url: http://localhost:4455/
      allowed_return_urls:
        - http://localhost:4455

      methods:
        password:
          enabled: false
        oidc:
          enabled: true
          config:
            providers:
              - id: google
                provider: google
                client_id: 588515455489-7egeqmvvgjmb5rmqdqo512rl0if499fs.apps.googleusercontent.com
                client_secret: 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
                mapper_url: file://oidc.google.jsonnet
                scope:
                  - email
  config.yaml: |
    version: v0.9.0-alpha.3
    serve:
      public:
        base_url: http://localhost:4433/
        cors:
          enabled: true
      admin:
        base_url: http://kratos:4434/

    selfservice:
      default_browser_return_url: http://localhost:4455/
      allowed_return_urls:
        - http://localhost:4455

      methods:
        password:
          enabled: false
        oidc:
          enabled: true
          config:
            providers:
              - id: github-app
                provider: github-app
                client_id: fake-value
                client_secret: another-fake-value
                mapper_url: file:///config/oidc.github.jsonnet
                scope:
                  - email

      flows:
        error:
          ui_url: http://localhost:4455/auth/error

        settings:
          ui_url: http://localhost:4455/api/kratos/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: http://localhost:4455/api/kratos/recovery

        verification:
          enabled: true
          ui_url: http://localhost:4455/api/kratos/verification
          after:
            default_browser_return_url: http://localhost:4455/

        logout:
          after:
            default_browser_return_url: http://localhost:4455

        login:
          ui_url: http://localhost:4455
          lifespan: 10m

        registration:
          lifespan: 10m
          ui_url: http://localhost:4455/account/register
          after:
            password:
              hooks:
                - hook: session
            oidc:
              hooks:
                - hook: session

    log:
      level: debug
      format: json
      leak_sensitive_values: true

    secrets:
      cookie:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
      cipher:
        - 32-LONG-SECRET-NOT-SECURE-AT-ALL

    ciphers:
      algorithm: xchacha20-poly1305

    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8

    identity:
      default_schema_id: user_v0
      schemas:
      - id: user_v0
        url: file:///config/identity_v0.schema.json

    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
  identity_v0.schema.json: |
    {
      "$id": "lunatrace-identity-schema",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "group": "password",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            },
            "name": {
              "title": "Name",
              "type": "string",
              "group": "profile"
            },
            "username": {
              "title": "Username",
              "type": "string",
              "group": "profile"
            },
            "website": {
              "title": "Website",
              "type": "string",
              "group": "profile"
            },
            "picture": {
              "title": "Picture",
              "type": "string",
              "group": "profile"
            },
            "profileUrl": {
              "title": "ProfileUrl",
              "type": "string",
              "group": "profile"
            },
            "githubId": {
              "title": "GithubId",
              "type": "string",
              "group": "profile"
            }
          },
          "required": [
            "email"
          ],
          "additionalProperties": false
        }
      }
    }
  oidc.google.jsonnet: |-
    local claims = {
      email_verified: true
    } + std.extVar('claims');

    {
      identity: {
        traits: {
          [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
          [if "given_name" in claims && claims.given_name then "first_name" else null]: claims.given_name,
          [if "family_name" in claims && claims.family_name then "last_name" else null]: claims.family_name,
          [if "hd" in claims && claims.email_verified then "hd" else null]: claims.hd,
        },
      },
    }
  oidc.hook.jsonnet: |
    function(ctx) { ctx: ctx }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kratos
  name: kratos-cm0
