table:
  name: config
  schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - id
        - key
        - value
      filter:
        key:
          _iregex: (ctf|user_mode|start|end|visibility|freeze)
  - role: user
    permission:
      columns:
        - id
        - key
        - value
      filter:
        key:
          _iregex: (ctf|user_mode|start|end|visibility|freeze)
