table:
  name: config
  schema: public
insert_permissions:
  - role: ctfd_admin
    permission:
      check: {}
      columns:
        - key
        - value
select_permissions:
  - role: ctfd_
    permission:
      columns:
        - id
        - key
        - value
      filter:
        key:
          _iregex: (ctf|user_mode|start|end|visibility|freeze)
  - role: ctfd_admin
    permission:
      columns:
        - id
        - key
        - value
      filter: {}
  - role: ctfd_user
    permission:
      columns:
        - id
        - key
        - value
      filter:
        key:
          _iregex: (ctf|user_mode|start|end|visibility|freeze)
update_permissions:
  - role: ctfd_admin
    permission:
      columns:
        - value
      filter: {}
      check: {}
